apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    istio-injection: enabled
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: policy-system