apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

resources:
  - ../../base
  - ../../blue-green
  - active-color.yaml

patches:
  - path: patch-delete-backend.yaml
  - path: patch-delete-hpa.yaml
  - path: patch-ingress.yaml
  - path: patch-blue-deployment.yaml
  - path: patch-green-deployment.yaml
  - path: patch-resourcequota.yaml

images:
  - name: backend-blue
    newName: 125156866917.dkr.ecr.us-east-1.amazonaws.com/mck21-devsecops-staging-backend
    newTag: sha-5137706
  - name: backend-green
    newName: 125156866917.dkr.ecr.us-east-1.amazonaws.com/mck21-devsecops-staging-backend
    newTag: sha-5137706
